# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/viady/Downloads/Basys3_Master.xdc

# XDC: C:/Users/viady/Downloads/xdc_additions.xdc

# Block Designs: bd/clocking_wizard/clocking_wizard.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clocking_wizard || ORIG_REF_NAME==clocking_wizard} -quiet] -quiet

# IP: bd/clocking_wizard/ip/clocking_wizard_clk_wiz_0_0/clocking_wizard_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clocking_wizard_clk_wiz_0_0 || ORIG_REF_NAME==clocking_wizard_clk_wiz_0_0} -quiet] -quiet

# XDC: C:/vivado_files/snake_vga_prezentare/snake_vga_prezentare.gen/sources_1/bd/clocking_wizard/clocking_wizard_ooc.xdc
